/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decrypt_secret.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(5dba587fa05d64de4e03f24eb57ccdaf)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <nacl/decrypt_secret.h>
// pydoc.h is automatically generated in the build directory
#include <decrypt_secret_pydoc.h>

void bind_decrypt_secret(py::module& m)
{

    using decrypt_secret = ::gr::nacl::decrypt_secret;


    py::class_<decrypt_secret,
               gr::block,
               gr::basic_block,
               std::shared_ptr<decrypt_secret>>(m, "decrypt_secret", D(decrypt_secret))

        .def(py::init(&decrypt_secret::make),
             py::arg("filename_key"),
             D(decrypt_secret, make))


        ;
}
