/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(decrypt_public.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(355ee8e78cd6ffa8c69af8adc74e084a)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nacl/decrypt_public.h>
// pydoc.h is automatically generated in the build directory
#include <decrypt_public_pydoc.h>

void bind_decrypt_public(py::module& m)
{

    using decrypt_public    = gr::nacl::decrypt_public;


    py::class_<decrypt_public, gr::block, gr::basic_block,
        std::shared_ptr<decrypt_public>>(m, "decrypt_public", D(decrypt_public))

        .def(py::init(&decrypt_public::make),
                py::arg("filename_pk"),
                py::arg("filename_sk"),
           D(decrypt_public,make)
        )
        



        ;




}








