/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(encrypt_public.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(8d7235b172de9b21b4d6ba9001720766)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nacl/encrypt_public.h>
// pydoc.h is automatically generated in the build directory
#include <encrypt_public_pydoc.h>

void bind_encrypt_public(py::module& m)
{

    using encrypt_public    = gr::nacl::encrypt_public;


    py::class_<encrypt_public, gr::block, gr::basic_block,
        std::shared_ptr<encrypt_public>>(m, "encrypt_public", D(encrypt_public))

        .def(py::init(&encrypt_public::make),
                py::arg("filename_pk"),
                py::arg("filename_sk"),
           D(encrypt_public,make)
        )
        



        ;




}








