/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(encrypt_secret.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(067b3d3907f9db4261bc3091006cb614)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nacl/encrypt_secret.h>
// pydoc.h is automatically generated in the build directory
#include <encrypt_secret_pydoc.h>

void bind_encrypt_secret(py::module& m)
{

    using encrypt_secret    = gr::nacl::encrypt_secret;


    py::class_<encrypt_secret, gr::block, gr::basic_block,
        std::shared_ptr<encrypt_secret>>(m, "encrypt_secret", D(encrypt_secret))

        .def(py::init(&encrypt_secret::make),
                py::arg("filename_key"),
           D(encrypt_secret,make)
        )
        



        ;




}








