/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(generate_keypair.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(1dbcd100b00403e738b84526025600ca)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nacl/generate_keypair.h>
// pydoc.h is automatically generated in the build directory
#include <generate_keypair_pydoc.h>

void bind_generate_keypair(py::module& m)
{

    using generate_keypair    = gr::nacl::generate_keypair;


    py::class_<generate_keypair, gr::block, gr::basic_block,
        std::shared_ptr<generate_keypair>>(m, "generate_keypair", D(generate_keypair))

        .def(py::init(&generate_keypair::make),
                py::arg("filename_sk"),
                py::arg("filename_pk"),
           D(generate_keypair,make)
        )
        



        ;




}








