/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(1)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(generate_key.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(c4fcac6d1c787349eaf2efd0fc512661)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/nacl/generate_key.h>
// pydoc.h is automatically generated in the build directory
#include <generate_key_pydoc.h>

void bind_generate_key(py::module& m)
{

    using generate_key    = gr::nacl::generate_key;


    py::class_<generate_key, gr::block, gr::basic_block,
        std::shared_ptr<generate_key>>(m, "generate_key", D(generate_key))

        .def(py::init(&generate_key::make),
                py::arg("filename_key"),
           D(generate_key,make)
        )
        



        ;




}








